---
openapi: 3.1.0
components:
  schemas:
    Customer:
      type: object
      required:
      - firstName
      - lastName
      - cprNumber
      - bankId
      properties:
        id:
          $ref: "#/components/schemas/UUID"
        firstName:
          type: string
          minLength: 1
        lastName:
          type: string
          minLength: 1
        cprNumber:
          type: string
          minLength: 1
        bankId:
          type: string
          minLength: 1
    Merchant:
      type: object
      required:
      - firstName
      - lastName
      - cprNumber
      - bankId
      properties:
        id:
          $ref: "#/components/schemas/UUID"
        firstName:
          type: string
          minLength: 1
        lastName:
          type: string
          minLength: 1
        cprNumber:
          type: string
          minLength: 1
        bankId:
          type: string
          minLength: 1
    Payment:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UUID"
        customer:
          $ref: "#/components/schemas/Customer"
        merchant:
          $ref: "#/components/schemas/Merchant"
        amount:
          type: number
        timestamp:
          type: string
        token:
          type: string
    PaymentRequest:
      type: object
      required:
      - merchantId
      - amount
      - token
      properties:
        merchantId:
          type: string
          minLength: 1
        amount:
          type: string
          minLength: 1
        token:
          type: string
          minLength: 1
    TokenRequest:
      type: object
      required:
      - customerId
      - numberOfTokens
      properties:
        customerId:
          type: string
          minLength: 1
        numberOfTokens:
          type: integer
          format: int32
    UUID:
      type: string
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
paths:
  /customers:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        "400":
          description: Bad Request
      summary: Register Customer
      tags:
      - Customer Resource
  /customers/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
      summary: Get Customer By Id
      tags:
      - Customer Resource
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
      summary: Delete Customer
      tags:
      - Customer Resource
  /customers/{id}/reports:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Payment"
      summary: Get Report
      tags:
      - Customer Resource
  /customers/{id}/tokens:
    post:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400":
          description: Bad Request
      summary: Request Tokens
      tags:
      - Customer Resource
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      summary: Get Tokens
      tags:
      - Customer Resource
  /merchants:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Merchant"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Merchant"
        "400":
          description: Bad Request
      summary: Register Merchant
      tags:
      - Merchant Resource
  /merchants/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Merchant"
      summary: Get Merchant By Id
      tags:
      - Merchant Resource
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
      summary: Delete Merchant
      tags:
      - Merchant Resource
  /merchants/{id}/reports:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Payment"
      summary: Get Report
      tags:
      - Merchant Resource
  /payments:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
        "400":
          description: Bad Request
      summary: Create Payment
      tags:
      - Payment Resource
  /payments/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
      summary: Get Payment By Id
      tags:
      - Payment Resource
  /reports:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Payment"
      summary: Get Manager Report
      tags:
      - Manager Resource
info:
  title: facade API
  version: 1.0.0-SNAPSHOT
